// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.0
// source: abci.proto

package abci

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Block struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Height        uint64                 `protobuf:"varint,1,opt,name=height,proto3" json:"height,omitempty"`
	ParentHash    []byte                 `protobuf:"bytes,2,opt,name=parent_hash,json=parentHash,proto3" json:"parent_hash,omitempty"` // 32 bytes
	View          uint64                 `protobuf:"varint,3,opt,name=view,proto3" json:"view,omitempty"`
	Proposer      uint64                 `protobuf:"varint,4,opt,name=proposer,proto3" json:"proposer,omitempty"`
	Payload       []byte                 `protobuf:"bytes,5,opt,name=payload,proto3" json:"payload,omitempty"`
	Hash          []byte                 `protobuf:"bytes,6,opt,name=hash,proto3" json:"hash,omitempty"` // 32 bytes
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Block) Reset() {
	*x = Block{}
	mi := &file_abci_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Block) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Block) ProtoMessage() {}

func (x *Block) ProtoReflect() protoreflect.Message {
	mi := &file_abci_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Block.ProtoReflect.Descriptor instead.
func (*Block) Descriptor() ([]byte, []int) {
	return file_abci_proto_rawDescGZIP(), []int{0}
}

func (x *Block) GetHeight() uint64 {
	if x != nil {
		return x.Height
	}
	return 0
}

func (x *Block) GetParentHash() []byte {
	if x != nil {
		return x.ParentHash
	}
	return nil
}

func (x *Block) GetView() uint64 {
	if x != nil {
		return x.View
	}
	return 0
}

func (x *Block) GetProposer() uint64 {
	if x != nil {
		return x.Proposer
	}
	return 0
}

func (x *Block) GetPayload() []byte {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *Block) GetHash() []byte {
	if x != nil {
		return x.Hash
	}
	return nil
}

type TxContext struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Height        uint64                 `protobuf:"varint,1,opt,name=height,proto3" json:"height,omitempty"`
	Epoch         uint64                 `protobuf:"varint,2,opt,name=epoch,proto3" json:"epoch,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TxContext) Reset() {
	*x = TxContext{}
	mi := &file_abci_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TxContext) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TxContext) ProtoMessage() {}

func (x *TxContext) ProtoReflect() protoreflect.Message {
	mi := &file_abci_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TxContext.ProtoReflect.Descriptor instead.
func (*TxContext) Descriptor() ([]byte, []int) {
	return file_abci_proto_rawDescGZIP(), []int{1}
}

func (x *TxContext) GetHeight() uint64 {
	if x != nil {
		return x.Height
	}
	return 0
}

func (x *TxContext) GetEpoch() uint64 {
	if x != nil {
		return x.Epoch
	}
	return 0
}

type ValidatorInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            uint64                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	PublicKey     []byte                 `protobuf:"bytes,2,opt,name=public_key,json=publicKey,proto3" json:"public_key,omitempty"`
	Power         uint64                 `protobuf:"varint,3,opt,name=power,proto3" json:"power,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ValidatorInfo) Reset() {
	*x = ValidatorInfo{}
	mi := &file_abci_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ValidatorInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ValidatorInfo) ProtoMessage() {}

func (x *ValidatorInfo) ProtoReflect() protoreflect.Message {
	mi := &file_abci_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ValidatorInfo.ProtoReflect.Descriptor instead.
func (*ValidatorInfo) Descriptor() ([]byte, []int) {
	return file_abci_proto_rawDescGZIP(), []int{2}
}

func (x *ValidatorInfo) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *ValidatorInfo) GetPublicKey() []byte {
	if x != nil {
		return x.PublicKey
	}
	return nil
}

func (x *ValidatorInfo) GetPower() uint64 {
	if x != nil {
		return x.Power
	}
	return 0
}

type ValidatorSet struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Validators    []*ValidatorInfo       `protobuf:"bytes,1,rep,name=validators,proto3" json:"validators,omitempty"`
	TotalPower    uint64                 `protobuf:"varint,2,opt,name=total_power,json=totalPower,proto3" json:"total_power,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ValidatorSet) Reset() {
	*x = ValidatorSet{}
	mi := &file_abci_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ValidatorSet) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ValidatorSet) ProtoMessage() {}

func (x *ValidatorSet) ProtoReflect() protoreflect.Message {
	mi := &file_abci_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ValidatorSet.ProtoReflect.Descriptor instead.
func (*ValidatorSet) Descriptor() ([]byte, []int) {
	return file_abci_proto_rawDescGZIP(), []int{3}
}

func (x *ValidatorSet) GetValidators() []*ValidatorInfo {
	if x != nil {
		return x.Validators
	}
	return nil
}

func (x *ValidatorSet) GetTotalPower() uint64 {
	if x != nil {
		return x.TotalPower
	}
	return 0
}

type BlockContext struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Height         uint64                 `protobuf:"varint,1,opt,name=height,proto3" json:"height,omitempty"`
	View           uint64                 `protobuf:"varint,2,opt,name=view,proto3" json:"view,omitempty"`
	Proposer       uint64                 `protobuf:"varint,3,opt,name=proposer,proto3" json:"proposer,omitempty"`
	Epoch          uint64                 `protobuf:"varint,4,opt,name=epoch,proto3" json:"epoch,omitempty"`
	EpochStartView uint64                 `protobuf:"varint,5,opt,name=epoch_start_view,json=epochStartView,proto3" json:"epoch_start_view,omitempty"`
	ValidatorSet   *ValidatorSet          `protobuf:"bytes,6,opt,name=validator_set,json=validatorSet,proto3" json:"validator_set,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *BlockContext) Reset() {
	*x = BlockContext{}
	mi := &file_abci_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BlockContext) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BlockContext) ProtoMessage() {}

func (x *BlockContext) ProtoReflect() protoreflect.Message {
	mi := &file_abci_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BlockContext.ProtoReflect.Descriptor instead.
func (*BlockContext) Descriptor() ([]byte, []int) {
	return file_abci_proto_rawDescGZIP(), []int{4}
}

func (x *BlockContext) GetHeight() uint64 {
	if x != nil {
		return x.Height
	}
	return 0
}

func (x *BlockContext) GetView() uint64 {
	if x != nil {
		return x.View
	}
	return 0
}

func (x *BlockContext) GetProposer() uint64 {
	if x != nil {
		return x.Proposer
	}
	return 0
}

func (x *BlockContext) GetEpoch() uint64 {
	if x != nil {
		return x.Epoch
	}
	return 0
}

func (x *BlockContext) GetEpochStartView() uint64 {
	if x != nil {
		return x.EpochStartView
	}
	return 0
}

func (x *BlockContext) GetValidatorSet() *ValidatorSet {
	if x != nil {
		return x.ValidatorSet
	}
	return nil
}

type EquivocationProof struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Validator     uint64                 `protobuf:"varint,1,opt,name=validator,proto3" json:"validator,omitempty"`
	View          uint64                 `protobuf:"varint,2,opt,name=view,proto3" json:"view,omitempty"`
	VoteType      uint32                 `protobuf:"varint,3,opt,name=vote_type,json=voteType,proto3" json:"vote_type,omitempty"` // 0 = Vote, 1 = Vote2
	BlockHashA    []byte                 `protobuf:"bytes,4,opt,name=block_hash_a,json=blockHashA,proto3" json:"block_hash_a,omitempty"`
	SignatureA    []byte                 `protobuf:"bytes,5,opt,name=signature_a,json=signatureA,proto3" json:"signature_a,omitempty"`
	BlockHashB    []byte                 `protobuf:"bytes,6,opt,name=block_hash_b,json=blockHashB,proto3" json:"block_hash_b,omitempty"`
	SignatureB    []byte                 `protobuf:"bytes,7,opt,name=signature_b,json=signatureB,proto3" json:"signature_b,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EquivocationProof) Reset() {
	*x = EquivocationProof{}
	mi := &file_abci_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EquivocationProof) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EquivocationProof) ProtoMessage() {}

func (x *EquivocationProof) ProtoReflect() protoreflect.Message {
	mi := &file_abci_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EquivocationProof.ProtoReflect.Descriptor instead.
func (*EquivocationProof) Descriptor() ([]byte, []int) {
	return file_abci_proto_rawDescGZIP(), []int{5}
}

func (x *EquivocationProof) GetValidator() uint64 {
	if x != nil {
		return x.Validator
	}
	return 0
}

func (x *EquivocationProof) GetView() uint64 {
	if x != nil {
		return x.View
	}
	return 0
}

func (x *EquivocationProof) GetVoteType() uint32 {
	if x != nil {
		return x.VoteType
	}
	return 0
}

func (x *EquivocationProof) GetBlockHashA() []byte {
	if x != nil {
		return x.BlockHashA
	}
	return nil
}

func (x *EquivocationProof) GetSignatureA() []byte {
	if x != nil {
		return x.SignatureA
	}
	return nil
}

func (x *EquivocationProof) GetBlockHashB() []byte {
	if x != nil {
		return x.BlockHashB
	}
	return nil
}

func (x *EquivocationProof) GetSignatureB() []byte {
	if x != nil {
		return x.SignatureB
	}
	return nil
}

type ValidatorUpdate struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            uint64                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	PublicKey     []byte                 `protobuf:"bytes,2,opt,name=public_key,json=publicKey,proto3" json:"public_key,omitempty"`
	Power         uint64                 `protobuf:"varint,3,opt,name=power,proto3" json:"power,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ValidatorUpdate) Reset() {
	*x = ValidatorUpdate{}
	mi := &file_abci_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ValidatorUpdate) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ValidatorUpdate) ProtoMessage() {}

func (x *ValidatorUpdate) ProtoReflect() protoreflect.Message {
	mi := &file_abci_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ValidatorUpdate.ProtoReflect.Descriptor instead.
func (*ValidatorUpdate) Descriptor() ([]byte, []int) {
	return file_abci_proto_rawDescGZIP(), []int{6}
}

func (x *ValidatorUpdate) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *ValidatorUpdate) GetPublicKey() []byte {
	if x != nil {
		return x.PublicKey
	}
	return nil
}

func (x *ValidatorUpdate) GetPower() uint64 {
	if x != nil {
		return x.Power
	}
	return 0
}

type EventAttribute struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Key           string                 `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Value         string                 `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EventAttribute) Reset() {
	*x = EventAttribute{}
	mi := &file_abci_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EventAttribute) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EventAttribute) ProtoMessage() {}

func (x *EventAttribute) ProtoReflect() protoreflect.Message {
	mi := &file_abci_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EventAttribute.ProtoReflect.Descriptor instead.
func (*EventAttribute) Descriptor() ([]byte, []int) {
	return file_abci_proto_rawDescGZIP(), []int{7}
}

func (x *EventAttribute) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *EventAttribute) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

type Event struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Type          string                 `protobuf:"bytes,1,opt,name=type,proto3" json:"type,omitempty"`
	Attributes    []*EventAttribute      `protobuf:"bytes,2,rep,name=attributes,proto3" json:"attributes,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Event) Reset() {
	*x = Event{}
	mi := &file_abci_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Event) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Event) ProtoMessage() {}

func (x *Event) ProtoReflect() protoreflect.Message {
	mi := &file_abci_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Event.ProtoReflect.Descriptor instead.
func (*Event) Descriptor() ([]byte, []int) {
	return file_abci_proto_rawDescGZIP(), []int{8}
}

func (x *Event) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *Event) GetAttributes() []*EventAttribute {
	if x != nil {
		return x.Attributes
	}
	return nil
}

type EndBlockResponse struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	ValidatorUpdates []*ValidatorUpdate     `protobuf:"bytes,1,rep,name=validator_updates,json=validatorUpdates,proto3" json:"validator_updates,omitempty"`
	Events           []*Event               `protobuf:"bytes,2,rep,name=events,proto3" json:"events,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *EndBlockResponse) Reset() {
	*x = EndBlockResponse{}
	mi := &file_abci_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EndBlockResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EndBlockResponse) ProtoMessage() {}

func (x *EndBlockResponse) ProtoReflect() protoreflect.Message {
	mi := &file_abci_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EndBlockResponse.ProtoReflect.Descriptor instead.
func (*EndBlockResponse) Descriptor() ([]byte, []int) {
	return file_abci_proto_rawDescGZIP(), []int{9}
}

func (x *EndBlockResponse) GetValidatorUpdates() []*ValidatorUpdate {
	if x != nil {
		return x.ValidatorUpdates
	}
	return nil
}

func (x *EndBlockResponse) GetEvents() []*Event {
	if x != nil {
		return x.Events
	}
	return nil
}

type Request struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Request:
	//
	//	*Request_CreatePayload
	//	*Request_ValidateBlock
	//	*Request_ValidateTx
	//	*Request_ExecuteBlock
	//	*Request_OnCommit
	//	*Request_OnEvidence
	//	*Request_Query
	Request       isRequest_Request `protobuf_oneof:"request"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Request) Reset() {
	*x = Request{}
	mi := &file_abci_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Request) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Request) ProtoMessage() {}

func (x *Request) ProtoReflect() protoreflect.Message {
	mi := &file_abci_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Request.ProtoReflect.Descriptor instead.
func (*Request) Descriptor() ([]byte, []int) {
	return file_abci_proto_rawDescGZIP(), []int{10}
}

func (x *Request) GetRequest() isRequest_Request {
	if x != nil {
		return x.Request
	}
	return nil
}

func (x *Request) GetCreatePayload() *BlockContext {
	if x != nil {
		if x, ok := x.Request.(*Request_CreatePayload); ok {
			return x.CreatePayload
		}
	}
	return nil
}

func (x *Request) GetValidateBlock() *ValidateBlockRequest {
	if x != nil {
		if x, ok := x.Request.(*Request_ValidateBlock); ok {
			return x.ValidateBlock
		}
	}
	return nil
}

func (x *Request) GetValidateTx() *ValidateTxRequest {
	if x != nil {
		if x, ok := x.Request.(*Request_ValidateTx); ok {
			return x.ValidateTx
		}
	}
	return nil
}

func (x *Request) GetExecuteBlock() *ExecuteBlockRequest {
	if x != nil {
		if x, ok := x.Request.(*Request_ExecuteBlock); ok {
			return x.ExecuteBlock
		}
	}
	return nil
}

func (x *Request) GetOnCommit() *OnCommitRequest {
	if x != nil {
		if x, ok := x.Request.(*Request_OnCommit); ok {
			return x.OnCommit
		}
	}
	return nil
}

func (x *Request) GetOnEvidence() *EquivocationProof {
	if x != nil {
		if x, ok := x.Request.(*Request_OnEvidence); ok {
			return x.OnEvidence
		}
	}
	return nil
}

func (x *Request) GetQuery() *QueryRequest {
	if x != nil {
		if x, ok := x.Request.(*Request_Query); ok {
			return x.Query
		}
	}
	return nil
}

type isRequest_Request interface {
	isRequest_Request()
}

type Request_CreatePayload struct {
	CreatePayload *BlockContext `protobuf:"bytes,1,opt,name=create_payload,json=createPayload,proto3,oneof"`
}

type Request_ValidateBlock struct {
	ValidateBlock *ValidateBlockRequest `protobuf:"bytes,2,opt,name=validate_block,json=validateBlock,proto3,oneof"`
}

type Request_ValidateTx struct {
	ValidateTx *ValidateTxRequest `protobuf:"bytes,3,opt,name=validate_tx,json=validateTx,proto3,oneof"`
}

type Request_ExecuteBlock struct {
	ExecuteBlock *ExecuteBlockRequest `protobuf:"bytes,4,opt,name=execute_block,json=executeBlock,proto3,oneof"`
}

type Request_OnCommit struct {
	OnCommit *OnCommitRequest `protobuf:"bytes,5,opt,name=on_commit,json=onCommit,proto3,oneof"`
}

type Request_OnEvidence struct {
	OnEvidence *EquivocationProof `protobuf:"bytes,6,opt,name=on_evidence,json=onEvidence,proto3,oneof"`
}

type Request_Query struct {
	Query *QueryRequest `protobuf:"bytes,7,opt,name=query,proto3,oneof"`
}

func (*Request_CreatePayload) isRequest_Request() {}

func (*Request_ValidateBlock) isRequest_Request() {}

func (*Request_ValidateTx) isRequest_Request() {}

func (*Request_ExecuteBlock) isRequest_Request() {}

func (*Request_OnCommit) isRequest_Request() {}

func (*Request_OnEvidence) isRequest_Request() {}

func (*Request_Query) isRequest_Request() {}

type ValidateBlockRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Block         *Block                 `protobuf:"bytes,1,opt,name=block,proto3" json:"block,omitempty"`
	Ctx           *BlockContext          `protobuf:"bytes,2,opt,name=ctx,proto3" json:"ctx,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ValidateBlockRequest) Reset() {
	*x = ValidateBlockRequest{}
	mi := &file_abci_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ValidateBlockRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ValidateBlockRequest) ProtoMessage() {}

func (x *ValidateBlockRequest) ProtoReflect() protoreflect.Message {
	mi := &file_abci_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ValidateBlockRequest.ProtoReflect.Descriptor instead.
func (*ValidateBlockRequest) Descriptor() ([]byte, []int) {
	return file_abci_proto_rawDescGZIP(), []int{11}
}

func (x *ValidateBlockRequest) GetBlock() *Block {
	if x != nil {
		return x.Block
	}
	return nil
}

func (x *ValidateBlockRequest) GetCtx() *BlockContext {
	if x != nil {
		return x.Ctx
	}
	return nil
}

type ValidateTxRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Tx            []byte                 `protobuf:"bytes,1,opt,name=tx,proto3" json:"tx,omitempty"`
	Ctx           *TxContext             `protobuf:"bytes,2,opt,name=ctx,proto3" json:"ctx,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ValidateTxRequest) Reset() {
	*x = ValidateTxRequest{}
	mi := &file_abci_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ValidateTxRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ValidateTxRequest) ProtoMessage() {}

func (x *ValidateTxRequest) ProtoReflect() protoreflect.Message {
	mi := &file_abci_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ValidateTxRequest.ProtoReflect.Descriptor instead.
func (*ValidateTxRequest) Descriptor() ([]byte, []int) {
	return file_abci_proto_rawDescGZIP(), []int{12}
}

func (x *ValidateTxRequest) GetTx() []byte {
	if x != nil {
		return x.Tx
	}
	return nil
}

func (x *ValidateTxRequest) GetCtx() *TxContext {
	if x != nil {
		return x.Ctx
	}
	return nil
}

type ExecuteBlockRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Txs           [][]byte               `protobuf:"bytes,1,rep,name=txs,proto3" json:"txs,omitempty"`
	Ctx           *BlockContext          `protobuf:"bytes,2,opt,name=ctx,proto3" json:"ctx,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExecuteBlockRequest) Reset() {
	*x = ExecuteBlockRequest{}
	mi := &file_abci_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExecuteBlockRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExecuteBlockRequest) ProtoMessage() {}

func (x *ExecuteBlockRequest) ProtoReflect() protoreflect.Message {
	mi := &file_abci_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExecuteBlockRequest.ProtoReflect.Descriptor instead.
func (*ExecuteBlockRequest) Descriptor() ([]byte, []int) {
	return file_abci_proto_rawDescGZIP(), []int{13}
}

func (x *ExecuteBlockRequest) GetTxs() [][]byte {
	if x != nil {
		return x.Txs
	}
	return nil
}

func (x *ExecuteBlockRequest) GetCtx() *BlockContext {
	if x != nil {
		return x.Ctx
	}
	return nil
}

type OnCommitRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Block         *Block                 `protobuf:"bytes,1,opt,name=block,proto3" json:"block,omitempty"`
	Ctx           *BlockContext          `protobuf:"bytes,2,opt,name=ctx,proto3" json:"ctx,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OnCommitRequest) Reset() {
	*x = OnCommitRequest{}
	mi := &file_abci_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OnCommitRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OnCommitRequest) ProtoMessage() {}

func (x *OnCommitRequest) ProtoReflect() protoreflect.Message {
	mi := &file_abci_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OnCommitRequest.ProtoReflect.Descriptor instead.
func (*OnCommitRequest) Descriptor() ([]byte, []int) {
	return file_abci_proto_rawDescGZIP(), []int{14}
}

func (x *OnCommitRequest) GetBlock() *Block {
	if x != nil {
		return x.Block
	}
	return nil
}

func (x *OnCommitRequest) GetCtx() *BlockContext {
	if x != nil {
		return x.Ctx
	}
	return nil
}

type QueryRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Path          string                 `protobuf:"bytes,1,opt,name=path,proto3" json:"path,omitempty"`
	Data          []byte                 `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *QueryRequest) Reset() {
	*x = QueryRequest{}
	mi := &file_abci_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QueryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueryRequest) ProtoMessage() {}

func (x *QueryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_abci_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueryRequest.ProtoReflect.Descriptor instead.
func (*QueryRequest) Descriptor() ([]byte, []int) {
	return file_abci_proto_rawDescGZIP(), []int{15}
}

func (x *QueryRequest) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *QueryRequest) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

type Response struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Response:
	//
	//	*Response_CreatePayload
	//	*Response_ValidateBlock
	//	*Response_ValidateTx
	//	*Response_ExecuteBlock
	//	*Response_OnCommit
	//	*Response_OnEvidence
	//	*Response_Query
	Response      isResponse_Response `protobuf_oneof:"response"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Response) Reset() {
	*x = Response{}
	mi := &file_abci_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Response) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Response) ProtoMessage() {}

func (x *Response) ProtoReflect() protoreflect.Message {
	mi := &file_abci_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Response.ProtoReflect.Descriptor instead.
func (*Response) Descriptor() ([]byte, []int) {
	return file_abci_proto_rawDescGZIP(), []int{16}
}

func (x *Response) GetResponse() isResponse_Response {
	if x != nil {
		return x.Response
	}
	return nil
}

func (x *Response) GetCreatePayload() *CreatePayloadResponse {
	if x != nil {
		if x, ok := x.Response.(*Response_CreatePayload); ok {
			return x.CreatePayload
		}
	}
	return nil
}

func (x *Response) GetValidateBlock() *ValidateBlockResponse {
	if x != nil {
		if x, ok := x.Response.(*Response_ValidateBlock); ok {
			return x.ValidateBlock
		}
	}
	return nil
}

func (x *Response) GetValidateTx() *ValidateTxResponse {
	if x != nil {
		if x, ok := x.Response.(*Response_ValidateTx); ok {
			return x.ValidateTx
		}
	}
	return nil
}

func (x *Response) GetExecuteBlock() *ExecuteBlockResponse {
	if x != nil {
		if x, ok := x.Response.(*Response_ExecuteBlock); ok {
			return x.ExecuteBlock
		}
	}
	return nil
}

func (x *Response) GetOnCommit() *OnCommitResponse {
	if x != nil {
		if x, ok := x.Response.(*Response_OnCommit); ok {
			return x.OnCommit
		}
	}
	return nil
}

func (x *Response) GetOnEvidence() *OnEvidenceResponse {
	if x != nil {
		if x, ok := x.Response.(*Response_OnEvidence); ok {
			return x.OnEvidence
		}
	}
	return nil
}

func (x *Response) GetQuery() *QueryResponse {
	if x != nil {
		if x, ok := x.Response.(*Response_Query); ok {
			return x.Query
		}
	}
	return nil
}

type isResponse_Response interface {
	isResponse_Response()
}

type Response_CreatePayload struct {
	CreatePayload *CreatePayloadResponse `protobuf:"bytes,1,opt,name=create_payload,json=createPayload,proto3,oneof"`
}

type Response_ValidateBlock struct {
	ValidateBlock *ValidateBlockResponse `protobuf:"bytes,2,opt,name=validate_block,json=validateBlock,proto3,oneof"`
}

type Response_ValidateTx struct {
	ValidateTx *ValidateTxResponse `protobuf:"bytes,3,opt,name=validate_tx,json=validateTx,proto3,oneof"`
}

type Response_ExecuteBlock struct {
	ExecuteBlock *ExecuteBlockResponse `protobuf:"bytes,4,opt,name=execute_block,json=executeBlock,proto3,oneof"`
}

type Response_OnCommit struct {
	OnCommit *OnCommitResponse `protobuf:"bytes,5,opt,name=on_commit,json=onCommit,proto3,oneof"`
}

type Response_OnEvidence struct {
	OnEvidence *OnEvidenceResponse `protobuf:"bytes,6,opt,name=on_evidence,json=onEvidence,proto3,oneof"`
}

type Response_Query struct {
	Query *QueryResponse `protobuf:"bytes,7,opt,name=query,proto3,oneof"`
}

func (*Response_CreatePayload) isResponse_Response() {}

func (*Response_ValidateBlock) isResponse_Response() {}

func (*Response_ValidateTx) isResponse_Response() {}

func (*Response_ExecuteBlock) isResponse_Response() {}

func (*Response_OnCommit) isResponse_Response() {}

func (*Response_OnEvidence) isResponse_Response() {}

func (*Response_Query) isResponse_Response() {}

type CreatePayloadResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Payload       []byte                 `protobuf:"bytes,1,opt,name=payload,proto3" json:"payload,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreatePayloadResponse) Reset() {
	*x = CreatePayloadResponse{}
	mi := &file_abci_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreatePayloadResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreatePayloadResponse) ProtoMessage() {}

func (x *CreatePayloadResponse) ProtoReflect() protoreflect.Message {
	mi := &file_abci_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreatePayloadResponse.ProtoReflect.Descriptor instead.
func (*CreatePayloadResponse) Descriptor() ([]byte, []int) {
	return file_abci_proto_rawDescGZIP(), []int{17}
}

func (x *CreatePayloadResponse) GetPayload() []byte {
	if x != nil {
		return x.Payload
	}
	return nil
}

type ValidateBlockResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ok            bool                   `protobuf:"varint,1,opt,name=ok,proto3" json:"ok,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ValidateBlockResponse) Reset() {
	*x = ValidateBlockResponse{}
	mi := &file_abci_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ValidateBlockResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ValidateBlockResponse) ProtoMessage() {}

func (x *ValidateBlockResponse) ProtoReflect() protoreflect.Message {
	mi := &file_abci_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ValidateBlockResponse.ProtoReflect.Descriptor instead.
func (*ValidateBlockResponse) Descriptor() ([]byte, []int) {
	return file_abci_proto_rawDescGZIP(), []int{18}
}

func (x *ValidateBlockResponse) GetOk() bool {
	if x != nil {
		return x.Ok
	}
	return false
}

type ValidateTxResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ok            bool                   `protobuf:"varint,1,opt,name=ok,proto3" json:"ok,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ValidateTxResponse) Reset() {
	*x = ValidateTxResponse{}
	mi := &file_abci_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ValidateTxResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ValidateTxResponse) ProtoMessage() {}

func (x *ValidateTxResponse) ProtoReflect() protoreflect.Message {
	mi := &file_abci_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ValidateTxResponse.ProtoReflect.Descriptor instead.
func (*ValidateTxResponse) Descriptor() ([]byte, []int) {
	return file_abci_proto_rawDescGZIP(), []int{19}
}

func (x *ValidateTxResponse) GetOk() bool {
	if x != nil {
		return x.Ok
	}
	return false
}

type ExecuteBlockResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Result        *EndBlockResponse      `protobuf:"bytes,1,opt,name=result,proto3" json:"result,omitempty"`
	Error         string                 `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExecuteBlockResponse) Reset() {
	*x = ExecuteBlockResponse{}
	mi := &file_abci_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExecuteBlockResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExecuteBlockResponse) ProtoMessage() {}

func (x *ExecuteBlockResponse) ProtoReflect() protoreflect.Message {
	mi := &file_abci_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExecuteBlockResponse.ProtoReflect.Descriptor instead.
func (*ExecuteBlockResponse) Descriptor() ([]byte, []int) {
	return file_abci_proto_rawDescGZIP(), []int{20}
}

func (x *ExecuteBlockResponse) GetResult() *EndBlockResponse {
	if x != nil {
		return x.Result
	}
	return nil
}

func (x *ExecuteBlockResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type OnCommitResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Error         string                 `protobuf:"bytes,1,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OnCommitResponse) Reset() {
	*x = OnCommitResponse{}
	mi := &file_abci_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OnCommitResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OnCommitResponse) ProtoMessage() {}

func (x *OnCommitResponse) ProtoReflect() protoreflect.Message {
	mi := &file_abci_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OnCommitResponse.ProtoReflect.Descriptor instead.
func (*OnCommitResponse) Descriptor() ([]byte, []int) {
	return file_abci_proto_rawDescGZIP(), []int{21}
}

func (x *OnCommitResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type OnEvidenceResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Error         string                 `protobuf:"bytes,1,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OnEvidenceResponse) Reset() {
	*x = OnEvidenceResponse{}
	mi := &file_abci_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OnEvidenceResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OnEvidenceResponse) ProtoMessage() {}

func (x *OnEvidenceResponse) ProtoReflect() protoreflect.Message {
	mi := &file_abci_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OnEvidenceResponse.ProtoReflect.Descriptor instead.
func (*OnEvidenceResponse) Descriptor() ([]byte, []int) {
	return file_abci_proto_rawDescGZIP(), []int{22}
}

func (x *OnEvidenceResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type QueryResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Data          []byte                 `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
	Error         string                 `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *QueryResponse) Reset() {
	*x = QueryResponse{}
	mi := &file_abci_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QueryResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueryResponse) ProtoMessage() {}

func (x *QueryResponse) ProtoReflect() protoreflect.Message {
	mi := &file_abci_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueryResponse.ProtoReflect.Descriptor instead.
func (*QueryResponse) Descriptor() ([]byte, []int) {
	return file_abci_proto_rawDescGZIP(), []int{23}
}

func (x *QueryResponse) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *QueryResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

var File_abci_proto protoreflect.FileDescriptor

const file_abci_proto_rawDesc = "" +
	"\n" +
	"\n" +
	"abci.proto\x12\fhotmint.abci\"\x9e\x01\n" +
	"\x05Block\x12\x16\n" +
	"\x06height\x18\x01 \x01(\x04R\x06height\x12\x1f\n" +
	"\vparent_hash\x18\x02 \x01(\fR\n" +
	"parentHash\x12\x12\n" +
	"\x04view\x18\x03 \x01(\x04R\x04view\x12\x1a\n" +
	"\bproposer\x18\x04 \x01(\x04R\bproposer\x12\x18\n" +
	"\apayload\x18\x05 \x01(\fR\apayload\x12\x12\n" +
	"\x04hash\x18\x06 \x01(\fR\x04hash\"9\n" +
	"\tTxContext\x12\x16\n" +
	"\x06height\x18\x01 \x01(\x04R\x06height\x12\x14\n" +
	"\x05epoch\x18\x02 \x01(\x04R\x05epoch\"T\n" +
	"\rValidatorInfo\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x04R\x02id\x12\x1d\n" +
	"\n" +
	"public_key\x18\x02 \x01(\fR\tpublicKey\x12\x14\n" +
	"\x05power\x18\x03 \x01(\x04R\x05power\"l\n" +
	"\fValidatorSet\x12;\n" +
	"\n" +
	"validators\x18\x01 \x03(\v2\x1b.hotmint.abci.ValidatorInfoR\n" +
	"validators\x12\x1f\n" +
	"\vtotal_power\x18\x02 \x01(\x04R\n" +
	"totalPower\"\xd7\x01\n" +
	"\fBlockContext\x12\x16\n" +
	"\x06height\x18\x01 \x01(\x04R\x06height\x12\x12\n" +
	"\x04view\x18\x02 \x01(\x04R\x04view\x12\x1a\n" +
	"\bproposer\x18\x03 \x01(\x04R\bproposer\x12\x14\n" +
	"\x05epoch\x18\x04 \x01(\x04R\x05epoch\x12(\n" +
	"\x10epoch_start_view\x18\x05 \x01(\x04R\x0eepochStartView\x12?\n" +
	"\rvalidator_set\x18\x06 \x01(\v2\x1a.hotmint.abci.ValidatorSetR\fvalidatorSet\"\xe8\x01\n" +
	"\x11EquivocationProof\x12\x1c\n" +
	"\tvalidator\x18\x01 \x01(\x04R\tvalidator\x12\x12\n" +
	"\x04view\x18\x02 \x01(\x04R\x04view\x12\x1b\n" +
	"\tvote_type\x18\x03 \x01(\rR\bvoteType\x12 \n" +
	"\fblock_hash_a\x18\x04 \x01(\fR\n" +
	"blockHashA\x12\x1f\n" +
	"\vsignature_a\x18\x05 \x01(\fR\n" +
	"signatureA\x12 \n" +
	"\fblock_hash_b\x18\x06 \x01(\fR\n" +
	"blockHashB\x12\x1f\n" +
	"\vsignature_b\x18\a \x01(\fR\n" +
	"signatureB\"V\n" +
	"\x0fValidatorUpdate\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x04R\x02id\x12\x1d\n" +
	"\n" +
	"public_key\x18\x02 \x01(\fR\tpublicKey\x12\x14\n" +
	"\x05power\x18\x03 \x01(\x04R\x05power\"8\n" +
	"\x0eEventAttribute\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value\"Y\n" +
	"\x05Event\x12\x12\n" +
	"\x04type\x18\x01 \x01(\tR\x04type\x12<\n" +
	"\n" +
	"attributes\x18\x02 \x03(\v2\x1c.hotmint.abci.EventAttributeR\n" +
	"attributes\"\x8b\x01\n" +
	"\x10EndBlockResponse\x12J\n" +
	"\x11validator_updates\x18\x01 \x03(\v2\x1d.hotmint.abci.ValidatorUpdateR\x10validatorUpdates\x12+\n" +
	"\x06events\x18\x02 \x03(\v2\x13.hotmint.abci.EventR\x06events\"\xea\x03\n" +
	"\aRequest\x12C\n" +
	"\x0ecreate_payload\x18\x01 \x01(\v2\x1a.hotmint.abci.BlockContextH\x00R\rcreatePayload\x12K\n" +
	"\x0evalidate_block\x18\x02 \x01(\v2\".hotmint.abci.ValidateBlockRequestH\x00R\rvalidateBlock\x12B\n" +
	"\vvalidate_tx\x18\x03 \x01(\v2\x1f.hotmint.abci.ValidateTxRequestH\x00R\n" +
	"validateTx\x12H\n" +
	"\rexecute_block\x18\x04 \x01(\v2!.hotmint.abci.ExecuteBlockRequestH\x00R\fexecuteBlock\x12<\n" +
	"\ton_commit\x18\x05 \x01(\v2\x1d.hotmint.abci.OnCommitRequestH\x00R\bonCommit\x12B\n" +
	"\von_evidence\x18\x06 \x01(\v2\x1f.hotmint.abci.EquivocationProofH\x00R\n" +
	"onEvidence\x122\n" +
	"\x05query\x18\a \x01(\v2\x1a.hotmint.abci.QueryRequestH\x00R\x05queryB\t\n" +
	"\arequest\"o\n" +
	"\x14ValidateBlockRequest\x12)\n" +
	"\x05block\x18\x01 \x01(\v2\x13.hotmint.abci.BlockR\x05block\x12,\n" +
	"\x03ctx\x18\x02 \x01(\v2\x1a.hotmint.abci.BlockContextR\x03ctx\"N\n" +
	"\x11ValidateTxRequest\x12\x0e\n" +
	"\x02tx\x18\x01 \x01(\fR\x02tx\x12)\n" +
	"\x03ctx\x18\x02 \x01(\v2\x17.hotmint.abci.TxContextR\x03ctx\"U\n" +
	"\x13ExecuteBlockRequest\x12\x10\n" +
	"\x03txs\x18\x01 \x03(\fR\x03txs\x12,\n" +
	"\x03ctx\x18\x02 \x01(\v2\x1a.hotmint.abci.BlockContextR\x03ctx\"j\n" +
	"\x0fOnCommitRequest\x12)\n" +
	"\x05block\x18\x01 \x01(\v2\x13.hotmint.abci.BlockR\x05block\x12,\n" +
	"\x03ctx\x18\x02 \x01(\v2\x1a.hotmint.abci.BlockContextR\x03ctx\"6\n" +
	"\fQueryRequest\x12\x12\n" +
	"\x04path\x18\x01 \x01(\tR\x04path\x12\x12\n" +
	"\x04data\x18\x02 \x01(\fR\x04data\"\xfb\x03\n" +
	"\bResponse\x12L\n" +
	"\x0ecreate_payload\x18\x01 \x01(\v2#.hotmint.abci.CreatePayloadResponseH\x00R\rcreatePayload\x12L\n" +
	"\x0evalidate_block\x18\x02 \x01(\v2#.hotmint.abci.ValidateBlockResponseH\x00R\rvalidateBlock\x12C\n" +
	"\vvalidate_tx\x18\x03 \x01(\v2 .hotmint.abci.ValidateTxResponseH\x00R\n" +
	"validateTx\x12I\n" +
	"\rexecute_block\x18\x04 \x01(\v2\".hotmint.abci.ExecuteBlockResponseH\x00R\fexecuteBlock\x12=\n" +
	"\ton_commit\x18\x05 \x01(\v2\x1e.hotmint.abci.OnCommitResponseH\x00R\bonCommit\x12C\n" +
	"\von_evidence\x18\x06 \x01(\v2 .hotmint.abci.OnEvidenceResponseH\x00R\n" +
	"onEvidence\x123\n" +
	"\x05query\x18\a \x01(\v2\x1b.hotmint.abci.QueryResponseH\x00R\x05queryB\n" +
	"\n" +
	"\bresponse\"1\n" +
	"\x15CreatePayloadResponse\x12\x18\n" +
	"\apayload\x18\x01 \x01(\fR\apayload\"'\n" +
	"\x15ValidateBlockResponse\x12\x0e\n" +
	"\x02ok\x18\x01 \x01(\bR\x02ok\"$\n" +
	"\x12ValidateTxResponse\x12\x0e\n" +
	"\x02ok\x18\x01 \x01(\bR\x02ok\"d\n" +
	"\x14ExecuteBlockResponse\x126\n" +
	"\x06result\x18\x01 \x01(\v2\x1e.hotmint.abci.EndBlockResponseR\x06result\x12\x14\n" +
	"\x05error\x18\x02 \x01(\tR\x05error\"(\n" +
	"\x10OnCommitResponse\x12\x14\n" +
	"\x05error\x18\x01 \x01(\tR\x05error\"*\n" +
	"\x12OnEvidenceResponse\x12\x14\n" +
	"\x05error\x18\x01 \x01(\tR\x05error\"9\n" +
	"\rQueryResponse\x12\x12\n" +
	"\x04data\x18\x01 \x01(\fR\x04data\x12\x14\n" +
	"\x05error\x18\x02 \x01(\tR\x05errorB<Z:github.com/rust-util-collections/hotmint/sdk/go/proto/abcib\x06proto3"

var (
	file_abci_proto_rawDescOnce sync.Once
	file_abci_proto_rawDescData []byte
)

func file_abci_proto_rawDescGZIP() []byte {
	file_abci_proto_rawDescOnce.Do(func() {
		file_abci_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_abci_proto_rawDesc), len(file_abci_proto_rawDesc)))
	})
	return file_abci_proto_rawDescData
}

var file_abci_proto_msgTypes = make([]protoimpl.MessageInfo, 24)
var file_abci_proto_goTypes = []any{
	(*Block)(nil),                 // 0: hotmint.abci.Block
	(*TxContext)(nil),             // 1: hotmint.abci.TxContext
	(*ValidatorInfo)(nil),         // 2: hotmint.abci.ValidatorInfo
	(*ValidatorSet)(nil),          // 3: hotmint.abci.ValidatorSet
	(*BlockContext)(nil),          // 4: hotmint.abci.BlockContext
	(*EquivocationProof)(nil),     // 5: hotmint.abci.EquivocationProof
	(*ValidatorUpdate)(nil),       // 6: hotmint.abci.ValidatorUpdate
	(*EventAttribute)(nil),        // 7: hotmint.abci.EventAttribute
	(*Event)(nil),                 // 8: hotmint.abci.Event
	(*EndBlockResponse)(nil),      // 9: hotmint.abci.EndBlockResponse
	(*Request)(nil),               // 10: hotmint.abci.Request
	(*ValidateBlockRequest)(nil),  // 11: hotmint.abci.ValidateBlockRequest
	(*ValidateTxRequest)(nil),     // 12: hotmint.abci.ValidateTxRequest
	(*ExecuteBlockRequest)(nil),   // 13: hotmint.abci.ExecuteBlockRequest
	(*OnCommitRequest)(nil),       // 14: hotmint.abci.OnCommitRequest
	(*QueryRequest)(nil),          // 15: hotmint.abci.QueryRequest
	(*Response)(nil),              // 16: hotmint.abci.Response
	(*CreatePayloadResponse)(nil), // 17: hotmint.abci.CreatePayloadResponse
	(*ValidateBlockResponse)(nil), // 18: hotmint.abci.ValidateBlockResponse
	(*ValidateTxResponse)(nil),    // 19: hotmint.abci.ValidateTxResponse
	(*ExecuteBlockResponse)(nil),  // 20: hotmint.abci.ExecuteBlockResponse
	(*OnCommitResponse)(nil),      // 21: hotmint.abci.OnCommitResponse
	(*OnEvidenceResponse)(nil),    // 22: hotmint.abci.OnEvidenceResponse
	(*QueryResponse)(nil),         // 23: hotmint.abci.QueryResponse
}
var file_abci_proto_depIdxs = []int32{
	2,  // 0: hotmint.abci.ValidatorSet.validators:type_name -> hotmint.abci.ValidatorInfo
	3,  // 1: hotmint.abci.BlockContext.validator_set:type_name -> hotmint.abci.ValidatorSet
	7,  // 2: hotmint.abci.Event.attributes:type_name -> hotmint.abci.EventAttribute
	6,  // 3: hotmint.abci.EndBlockResponse.validator_updates:type_name -> hotmint.abci.ValidatorUpdate
	8,  // 4: hotmint.abci.EndBlockResponse.events:type_name -> hotmint.abci.Event
	4,  // 5: hotmint.abci.Request.create_payload:type_name -> hotmint.abci.BlockContext
	11, // 6: hotmint.abci.Request.validate_block:type_name -> hotmint.abci.ValidateBlockRequest
	12, // 7: hotmint.abci.Request.validate_tx:type_name -> hotmint.abci.ValidateTxRequest
	13, // 8: hotmint.abci.Request.execute_block:type_name -> hotmint.abci.ExecuteBlockRequest
	14, // 9: hotmint.abci.Request.on_commit:type_name -> hotmint.abci.OnCommitRequest
	5,  // 10: hotmint.abci.Request.on_evidence:type_name -> hotmint.abci.EquivocationProof
	15, // 11: hotmint.abci.Request.query:type_name -> hotmint.abci.QueryRequest
	0,  // 12: hotmint.abci.ValidateBlockRequest.block:type_name -> hotmint.abci.Block
	4,  // 13: hotmint.abci.ValidateBlockRequest.ctx:type_name -> hotmint.abci.BlockContext
	1,  // 14: hotmint.abci.ValidateTxRequest.ctx:type_name -> hotmint.abci.TxContext
	4,  // 15: hotmint.abci.ExecuteBlockRequest.ctx:type_name -> hotmint.abci.BlockContext
	0,  // 16: hotmint.abci.OnCommitRequest.block:type_name -> hotmint.abci.Block
	4,  // 17: hotmint.abci.OnCommitRequest.ctx:type_name -> hotmint.abci.BlockContext
	17, // 18: hotmint.abci.Response.create_payload:type_name -> hotmint.abci.CreatePayloadResponse
	18, // 19: hotmint.abci.Response.validate_block:type_name -> hotmint.abci.ValidateBlockResponse
	19, // 20: hotmint.abci.Response.validate_tx:type_name -> hotmint.abci.ValidateTxResponse
	20, // 21: hotmint.abci.Response.execute_block:type_name -> hotmint.abci.ExecuteBlockResponse
	21, // 22: hotmint.abci.Response.on_commit:type_name -> hotmint.abci.OnCommitResponse
	22, // 23: hotmint.abci.Response.on_evidence:type_name -> hotmint.abci.OnEvidenceResponse
	23, // 24: hotmint.abci.Response.query:type_name -> hotmint.abci.QueryResponse
	9,  // 25: hotmint.abci.ExecuteBlockResponse.result:type_name -> hotmint.abci.EndBlockResponse
	26, // [26:26] is the sub-list for method output_type
	26, // [26:26] is the sub-list for method input_type
	26, // [26:26] is the sub-list for extension type_name
	26, // [26:26] is the sub-list for extension extendee
	0,  // [0:26] is the sub-list for field type_name
}

func init() { file_abci_proto_init() }
func file_abci_proto_init() {
	if File_abci_proto != nil {
		return
	}
	file_abci_proto_msgTypes[10].OneofWrappers = []any{
		(*Request_CreatePayload)(nil),
		(*Request_ValidateBlock)(nil),
		(*Request_ValidateTx)(nil),
		(*Request_ExecuteBlock)(nil),
		(*Request_OnCommit)(nil),
		(*Request_OnEvidence)(nil),
		(*Request_Query)(nil),
	}
	file_abci_proto_msgTypes[16].OneofWrappers = []any{
		(*Response_CreatePayload)(nil),
		(*Response_ValidateBlock)(nil),
		(*Response_ValidateTx)(nil),
		(*Response_ExecuteBlock)(nil),
		(*Response_OnCommit)(nil),
		(*Response_OnEvidence)(nil),
		(*Response_Query)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_abci_proto_rawDesc), len(file_abci_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   24,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_abci_proto_goTypes,
		DependencyIndexes: file_abci_proto_depIdxs,
		MessageInfos:      file_abci_proto_msgTypes,
	}.Build()
	File_abci_proto = out.File
	file_abci_proto_goTypes = nil
	file_abci_proto_depIdxs = nil
}
